backend:
  name: git-gateway
  repo: holaplex/devtools.holaplex.com
  branch: master # Branch to update (optional; defaults to master)
local_backend: true
media_folder: public/uploads
public_folder: uploads
